[project]
name = "cadnet"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy==1.26.4",
    "pandas==2.2.3",
    "pyarrow==17.0.0",
    "scikit-learn==1.1.3",
    "torch==2.0.1"
]